basic_auth_string: ENC[AES256_GCM,data:GWLTYLIKbXnZL/TRTfqHMsvHy0Ex130bQTbH/xZJ7ks=,iv:eVJSWaRs7P3LZxAnCLIjDiGrhNGHpo97cmxB88SUkRM=,tag:GoXuGvLLwOkM3A2KDRNp4w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:873276765047:key/345d5aee-c404-43cd-b700-da9d01258d9f
          created_at: "2025-02-08T18:23:27Z"
          enc: AQICAHgtdyIL/RRO/gZq1Fo/LDdkvYD75k9xnOxiBRDKRvjM7AF75waC+VNzgDVJMelSomv7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5l34ARfMzLShvXJJAgEQgDt/3JRw/P8swh/ZSllN9rz2rG6vR5JVH3QOcj6VxDJUkXLvAUmfAVZgCyHoJO48hFe399NIKJaFCZcYvA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-08T18:23:44Z"
    mac: ENC[AES256_GCM,data:srejzfo0NRvh5hT+l/aG1JtXQSXL0IwJF2bksNUOxJmjQwZelCYu2qxq4Mvi8/Rgg7rJPqXB940kxxNRL1md+diAsv40H6IBLqVvjseoyAn1QdWN7xDwZDMjEyFGuA8pRx3TyDvPnR7MHQY00pJiqLNhTAqv3ECsOtCVj4H8DsM=,iv:joziCbh/Xo8hWcoWxBANfyDIqB2Eyj6QCuUlqTCKc8E=,tag:PewXPVcDbLnzndmola12yg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
